#!/bin/bash

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

killall polybar

if [xrandr --prop |grep -q "VGA-1-1 connected"] ; then
	xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --output VGA-1-1 --mode 1920x1080 --pos 1920x0
	bspc monitor VGA-1-1 -d 2 3 4 5 6 7 8 9 10
	bspc monitor eDP-1-1 -d 1
	polybar monitor &
	polybar laptop &
elif [xrandr --prop |grep -q "eDP-1 connected"] ; then
	xrandr --output eDP-1 --mode 1920x1080 --pos 0x0 --rotate normal
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7
	polybar laptop &
else	
	xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7
	polybar laptop &
fi

bspc config border_width 3
bspc config window_gap 3 
bspc config top_padding 5
bspc config focus_follows_pointer true

bspc config focused_border_color \#61AFEF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rile -a TelegramDesktop desktop=4

